name: Docker Image CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 获取参数
      run: |
        echo "GITHUB_REF_NAME=${{github.ref_name}}" > config.propertis
    - name: 生成Dockerfile文件
      run: |
        chmod +x check_version.sh
        chmod +x generate_dockerfile.sh
        ./check_version.sh
        cat Dockerfile
