name: Docker Image CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 生成Dockerfile文件
      run: |
        chmod +x check_version.sh
        ./check_version.sh
    - name: check dockerfile
      id: dockerfile_check
      uses: andstor/file-existence-action@v1
      with:
         files: "Dockerfile"
    - name: 如果没有生成dockerfile提前结束工作流
      if: steps.dockerfile_check.outputs.filesExists != 'true' 
      uses: actions/github-script@v6
      with:
        script: |
          core.exit
    - name: Substitute version
      id: get_frp_version
      run: |
        echo "frp_version=$(cat version.file)" >> $GITHUB_ENV
    - name: Login to Docker hub
      uses: docker/login-action@v2
      with:
        username: itodouble
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      env:
        FRP_VERSION: ${{ env.frp_version }}
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: |
          itodouble/frp:latest
          itodouble/frp:${{ env.FRP_VERSION }}
