name: Docker Image CI

on:
  workflow_dispatch:
  push:
    tags: "*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 获取参数
      run: |
        echo "github: ${{ toJSON(github) }}"
    - name: 构建Dockerfile
      run: |
        chmox +x generate_dockerfile.sh
        ./generate_dockerfile.sh
        cat Dockerfile
    - name: Login to Docker hub
      uses: docker/login-action@v2
      with:
        username: itodouble
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: |
          itodouble/frp:latest
          itodouble/frp:${{github.ref_name}}
        args: |
          -e GITHUB_REF_NAME=${{github.ref_name}}
